/* tslint:disable */
/* eslint-disable */
/**
 * Vox
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecordingItem } from './RecordingItem';
import {
    RecordingItemFromJSON,
    RecordingItemFromJSONTyped,
    RecordingItemToJSON,
    RecordingItemToJSONTyped,
} from './RecordingItem';

/**
 * 
 * @export
 * @interface ListRecordingResponse
 */
export interface ListRecordingResponse {
    /**
     * 
     * @type {Array<RecordingItem>}
     * @memberof ListRecordingResponse
     */
    recordings: Array<RecordingItem>;
}

/**
 * Check if a given object implements the ListRecordingResponse interface.
 */
export function instanceOfListRecordingResponse(value: object): value is ListRecordingResponse {
    if (!('recordings' in value) || value['recordings'] === undefined) return false;
    return true;
}

export function ListRecordingResponseFromJSON(json: any): ListRecordingResponse {
    return ListRecordingResponseFromJSONTyped(json, false);
}

export function ListRecordingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListRecordingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'recordings': ((json['recordings'] as Array<any>).map(RecordingItemFromJSON)),
    };
}

export function ListRecordingResponseToJSON(json: any): ListRecordingResponse {
    return ListRecordingResponseToJSONTyped(json, false);
}

export function ListRecordingResponseToJSONTyped(value?: ListRecordingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recordings': ((value['recordings'] as Array<any>).map(RecordingItemToJSON)),
    };
}

