/* tslint:disable */
/* eslint-disable */
/**
 * Vox
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewRecordingResponse
 */
export interface NewRecordingResponse {
    /**
     * 
     * @type {string}
     * @memberof NewRecordingResponse
     */
    message: string;
}

/**
 * Check if a given object implements the NewRecordingResponse interface.
 */
export function instanceOfNewRecordingResponse(value: object): value is NewRecordingResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function NewRecordingResponseFromJSON(json: any): NewRecordingResponse {
    return NewRecordingResponseFromJSONTyped(json, false);
}

export function NewRecordingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewRecordingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function NewRecordingResponseToJSON(json: any): NewRecordingResponse {
    return NewRecordingResponseToJSONTyped(json, false);
}

export function NewRecordingResponseToJSONTyped(value?: NewRecordingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

