/* tslint:disable */
/* eslint-disable */
/**
 * Vox
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthResponse,
  HTTPValidationError,
  ListRecordingResponse,
  LoginRequest,
  NewRecordingResponse,
  PingResponse,
  RegisterRequest,
} from '../models/index';
import {
    AuthResponseFromJSON,
    AuthResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListRecordingResponseFromJSON,
    ListRecordingResponseToJSON,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    NewRecordingResponseFromJSON,
    NewRecordingResponseToJSON,
    PingResponseFromJSON,
    PingResponseToJSON,
    RegisterRequestFromJSON,
    RegisterRequestToJSON,
} from '../models/index';

export interface LoginApiAuthLoginPostRequest {
    loginRequest: LoginRequest;
}

export interface NewRecordingApiRecordingPostRequest {
    recording: Blob;
}

export interface RegisterApiAuthRegisterPostRequest {
    registerRequest: RegisterRequest;
}

/**
 * 
 */
export class ApiApi extends runtime.BaseAPI {

    /**
     * List Recording
     */
    async listRecordingApiRecordingGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListRecordingResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/recording/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListRecordingResponseFromJSON(jsonValue));
    }

    /**
     * List Recording
     */
    async listRecordingApiRecordingGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListRecordingResponse> {
        const response = await this.listRecordingApiRecordingGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Login
     */
    async loginApiAuthLoginPostRaw(requestParameters: LoginApiAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthResponse>> {
        if (requestParameters['loginRequest'] == null) {
            throw new runtime.RequiredError(
                'loginRequest',
                'Required parameter "loginRequest" was null or undefined when calling loginApiAuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseFromJSON(jsonValue));
    }

    /**
     * Login
     */
    async loginApiAuthLoginPost(requestParameters: LoginApiAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthResponse> {
        const response = await this.loginApiAuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * New Recording
     */
    async newRecordingApiRecordingPostRaw(requestParameters: NewRecordingApiRecordingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NewRecordingResponse>> {
        if (requestParameters['recording'] == null) {
            throw new runtime.RequiredError(
                'recording',
                'Required parameter "recording" was null or undefined when calling newRecordingApiRecordingPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['recording'] != null) {
            formParams.append('recording', requestParameters['recording'] as any);
        }


        let urlPath = `/api/recording/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NewRecordingResponseFromJSON(jsonValue));
    }

    /**
     * New Recording
     */
    async newRecordingApiRecordingPost(requestParameters: NewRecordingApiRecordingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NewRecordingResponse> {
        const response = await this.newRecordingApiRecordingPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * pings the api, requires authentication useful to check if you have a valid cookie
     * Ping
     */
    async pingApiPingGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PingResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/ping`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PingResponseFromJSON(jsonValue));
    }

    /**
     * pings the api, requires authentication useful to check if you have a valid cookie
     * Ping
     */
    async pingApiPingGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PingResponse> {
        const response = await this.pingApiPingGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Register
     */
    async registerApiAuthRegisterPostRaw(requestParameters: RegisterApiAuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthResponse>> {
        if (requestParameters['registerRequest'] == null) {
            throw new runtime.RequiredError(
                'registerRequest',
                'Required parameter "registerRequest" was null or undefined when calling registerApiAuthRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/auth/register`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterRequestToJSON(requestParameters['registerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseFromJSON(jsonValue));
    }

    /**
     * Register
     */
    async registerApiAuthRegisterPost(requestParameters: RegisterApiAuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthResponse> {
        const response = await this.registerApiAuthRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
