/* tslint:disable */
/* eslint-disable */
/**
 * Vox
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  ListRecordingResponse,
  NewRecordingResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListRecordingResponseFromJSON,
    ListRecordingResponseToJSON,
    NewRecordingResponseFromJSON,
    NewRecordingResponseToJSON,
} from '../models/index';

export interface NewRecordingApiRecordingPostRequest {
    recording: Blob;
}

/**
 * 
 */
export class RecordingApi extends runtime.BaseAPI {

    /**
     * List Recording
     */
    async listRecordingApiRecordingGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListRecordingResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/recording/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListRecordingResponseFromJSON(jsonValue));
    }

    /**
     * List Recording
     */
    async listRecordingApiRecordingGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListRecordingResponse> {
        const response = await this.listRecordingApiRecordingGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * New Recording
     */
    async newRecordingApiRecordingPostRaw(requestParameters: NewRecordingApiRecordingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NewRecordingResponse>> {
        if (requestParameters['recording'] == null) {
            throw new runtime.RequiredError(
                'recording',
                'Required parameter "recording" was null or undefined when calling newRecordingApiRecordingPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['recording'] != null) {
            formParams.append('recording', requestParameters['recording'] as any);
        }


        let urlPath = `/api/recording/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NewRecordingResponseFromJSON(jsonValue));
    }

    /**
     * New Recording
     */
    async newRecordingApiRecordingPost(requestParameters: NewRecordingApiRecordingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NewRecordingResponse> {
        const response = await this.newRecordingApiRecordingPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
