version: '3'

vars:
  IMAGE_BASE: vox
  TARGET: "develop"
  PYSRV: "src"
  UI: "ui"

tasks:
  default:
    cmds:
      - task --list --sort=alphanumeric
    silent: true

  dkb:
    desc: "Builds the main image for a specific target. Usage: task dk:b:<target>"
    cmds:
      - docker build . -t {{.IMAGE_BASE}}:{{.TARGET}}
    preconditions:
      - sh: 'test -n "{{.TARGET}}"'
        msg: "The 'target' variable must be provided. Usage: task dk.<target-name>"

  dk:
    desc: "Builds and runs the main image. Usage: task dk"
    cmds:
      - task: dkb
      - docker run --rm 
          -e origins=http://localhost:8992 
          -p 8992:8000 
        {{.IMAGE_BASE}}:{{.TARGET}}
    preconditions:
      - sh: 'test -n "{{.TARGET}}"'
        msg: "The 'target' variable must be provided. Usage: task dk:r.<target-name>"

  py:srv:*:
    desc: "creates a service, handler, model file with dir in {{ .PYSRV }}"
    dir: src
    vars:
      SERVICE_NAME: "{{index .MATCH 0}}"
    cmds:
      - coreutils mkdir -p
      - coreutils touch

  spec:
    cmds:
      - uv run -m src.openapi -o ./spec
      - task: spec:generate

  spec:generate:
    dir: spec
    vars:
      TMP_GEN: "gen/web"
      IMG: "openapi-generator"
      PACKAGE_NAME: "../ui/src/openapi"
    cmds:
      - coreutils rm -rf {{ .TMP_GEN }}
      - docker run --rm 
          -v ./:/local 
          -v ./{{ .TMP_GEN }}:/output/dart/ 
        openapitools/openapi-generator-cli generate 
          -i /local/openapi.json 
          -g typescript-fetch
          -o /output/dart/

      - coreutils mkdir -p {{ .PACKAGE_NAME }}
      - coreutils rm -rf {{ .PACKAGE_NAME }}
      - coreutils mv -f ./{{ .TMP_GEN }} {{ .PACKAGE_NAME }}
